/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_encode_client_hello: (a: number, b: number) => [number, number, number, number];
export const wasm_init: () => [number, number, number, number];
export const wasm_on_handshake_timeout: () => void;
export const wasm_on_shadow_result: (a: number, b: number) => void;
export const wasm_on_websocket_message: (a: number, b: number) => void;
export const wasm_send_message: (a: number, b: number) => [number, number];
export const wasm_start_game: () => void;
export const wasm_tick: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h982eed14cf430e42: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h45409842cfc42ca0: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h14fb53fd931fe28c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0303316257e55131: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha1ca2ebc91a73f21: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h283b026338f9b503: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h33f004939760aea9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h93c781489a5e80a5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2afbaf96985aab62: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha29bc205405ba151: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb9a54380b6de4600: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__hc3996ebc4deeaaa0: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6999338c3bcd4b83: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
