/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_encode_client_hello: (a: number, b: number) => [number, number, number, number];
export const wasm_init: () => [number, number, number, number];
export const wasm_on_handshake_timeout: () => void;
export const wasm_on_shadow_result: (a: number, b: number) => void;
export const wasm_on_websocket_message: (a: number, b: number) => void;
export const wasm_send_message: (a: number, b: number) => [number, number];
export const wasm_start_game: () => void;
export const wasm_tick: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h982eed14cf430e42: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h43d8cbcd7620786a: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hbf11878112de8321: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h08d848fcabd95ebf: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha3b2e3e6975b995a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h083ae3e5125011c8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h65b1dcdf538474dd: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4005bc30c83f3d30: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h40c69f3b057a1916: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5e786c18403bebe7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb9a54380b6de4600: (a: number, b: number) => number;
export const wasm_bindgen__convert__closures_____invoke__h05feebdc2d11e6bf: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5c982496db70eb3e: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
