[package]
name = "bevy_runtime"
version = "0.1.0"
edition = "2021"

[features]
plaintext-assets = []
debug-mode = []
hot-reload-native = ["notify", "crossbeam-channel"]
hot-reload-wasm = []

[dependencies]
bevy = { workspace = true }
bevy_rapier3d = { workspace = true }
vm_bevy_bridge = { path = "../vm_bevy_bridge" }
vm_runtime = { path = "../vm_runtime" }
deterministic = { path = "../deterministic" }
crypto = { path = "../crypto" }
asset_manifest = { path = "../asset_manifest" }
zeroize = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
rhai = { workspace = true }
serde_json = { workspace = true }
bridge_types = { path = "../bridge_types" }
netcode = { path = "../netcode" }
noise = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
notify = { version = "6", optional = true }
crossbeam-channel = { version = "0.5", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["WebSocket", "MessageEvent", "ErrorEvent", "CloseEvent", "Window", "Performance"] }

[dev-dependencies]
tempfile = "3"
