[package]
name = "manifest-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
asset_manifest = { path = "../../engine/asset_manifest" }
blake3 = { workspace = true }
clap = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
walkdir = { workspace = true }
